### PR TITLE
Issue/190/design sign in form

### PR DESCRIPTION
**Pull request by yoavz1997**
All the user-end parts in this form are done. After the whole UI is finished the back-end support will be added

### CODE REVIEW

**Comment by yoavz1997** [comment]
The Travis check failed due to code in the SimpleWebParser tests. Checking now

**Comment by yoavz1997** [comment]
I'm not sure, why one Travis check pass, and another does not... @ofiralexi @ShaiZeevi @saifun @matanpugach @YarinSh @Itamaror any ideas?

**Comment by ofiralexi** [comment]
@yoavz1997 I found this discussion in stackoverflow regarding your issue, want to check if it works ?
https://stackoverflow.com/questions/41524861/travis-failed-push-but-passed-pr

**Comment by ofiralexi** [comment]
@yoavz1997 the merge passed, keeping it on develop. 
image

**Pull request merged**
